# Site settings
title: "Peachy Clean"
description: "site description goes here"

url: "http://example.com"

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass
  style: compressed